apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoapi
  namespace: echoapi-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: echoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echoapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echoapi
    spec:
      containers:
        - name: echoapi
          image: quay.io/3scale/echoapi:stable
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9292
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: echoapi
  namespace: echoapi-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: echoapi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: echoapi
  ports:
    - name: http
      port: 9292
      targetPort: http
