apiVersion: v1
kind: Namespace
metadata:
  name: echoapi-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: echoapi
    argocd.argoproj.io/managed-by: openshift-gitops
