apiVersion: v1
kind: Secret
metadata:
  name: new-product-existing-client-prod
  namespace: 3scale-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  clientId: "b2e33135"
  clientSecret: "54afa66a3d030da9daf7cdecb966e3fa" # notsecret - test data
  accountOrgName: "Echo API Org"
  productSystemName: "myapi_oidc_existing"
  planSystemName: "basic-myapi-oidc"
  appName: "new-product-existing-client-app"
  appDescription: "new-product-existing-client-app"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: new-product-existing-client-prod # name do application
  namespace: 3scale-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: register
          image: registry.access.redhat.com/ubi9/python-311:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail
              python3 /scripts/register.py
          env:
            - name: ACCOUNT_ORG_NAME
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: accountOrgName
            - name: PRODUCT_SYSTEM_NAME
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: productSystemName
            - name: PLAN_SYSTEM_NAME
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: planSystemName
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: appName
            - name: APP_DESCRIPTION
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: appDescription
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: new-product-existing-client-prod
                  key: clientSecret
            - name: ADMIN_URL
              valueFrom:
                secretKeyRef:
                  name: myapi-oidc-3scale-management
                  key: adminURL
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: myapi-oidc-3scale-management
                  key: token
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: register-application-script
            defaultMode: 0444
