apiVersion: v1
kind: Namespace
metadata:
  name: 3scale-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  labels:
    app.kubernetes.io/name: 3scale
    argocd.argoproj.io/managed-by: openshift-gitops
