apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
  namespace: 3scale-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  channel: threescale-2.16
  installPlanApproval: Manual
  name: 3scale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
